networks:
  autoscale:
  monitoring:
    name: monitoring_default
    external: true
  proxy_channel:
    name: proxy_channel
    external: true
  monitoring_channel:
    name: monitoring_channel
    external: true

services:
  this:
    image: jcwimer/docker-swarm-autoscaler:0.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PROMETHEUS_URL=http://monitoring_prometheus:9090
    networks:
      - autoscale
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.10"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

