services:
  prune_nodes:
    image: docker
    command: ["docker", "system", "prune", "--force", "--volumes"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=1 12 * * 7"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

  removed_downed_nodes:
    image: docker
    command: >
      docker node ls --format "{{.ID}} {{.Status}}" | awk '$2=="Down" {print $1}' | xargs -r docker node rm --force
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=1 12 * * 7"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

#  refresh_login_token:
#    image: docker
#    command: [ "docker", "login", "${ADDRESS}", "--username", "${USERNAME}", "--password", "${PASSWORD}" ]
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      mode: global
#      labels:
#        - "swarm.cronjob.enable=true"
#        - "swarm.cronjob.schedule=0 */30 * * * *"
#        - "swarm.cronjob.skip-running=false"
#      restart_policy:
#        condition: none
