services:
  swarm-dashboard:
    image: mohsenasm/swarm-dashboard:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Dhaka"
      ENABLE_AUTHENTICATION: "false"
      ENABLE_HTTPS: "false"
      NODE_EXPORTER_SERVICE_NAME_REGEX: "node-exporter"
      CADVISOR_SERVICE_NAME_REGEX: "cadvisor"
    networks:
      - default
      - proxy_channel
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_channel
        - traefik.http.routers.monitoring-dashboard.entrypoints=web,websecure
        - traefik.http.routers.monitoring-dashboard.middlewares=google-oidc-auth@file,redirectToHttps@file
        - traefik.http.routers.monitoring-dashboard.rule=Host(`dashboard.${root_domain}`)
        - traefik.http.services.monitoring-dashboard.loadbalancer.server.port=8080

  grafana:
    image: grafana/grafana:11.5.1
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_GOOGLE_ENABLED=false
    networks:
      - default
      - proxy_channel
      - monitoring_channel
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_channel
        - traefik.http.routers.monitoring-grafana.entrypoints=web,websecure
        - traefik.http.routers.monitoring-grafana.middlewares=google-oidc-auth@file,redirectToHttps@file
        - traefik.http.routers.monitoring-grafana.rule=Host(`grafana.${root_domain}`)
        - traefik.http.services.monitoring-grafana.loadbalancer.server.port=3000

  prometheus:
    image: prom/prometheus:v3.0.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=24h'
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - type: volume
        source: prometheus-data
        target: /prometheus
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - default
      - socat
      - monitoring_channel
      - proxy_channel
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - logs.collector=loki
        - traefik.enable=true
        - traefik.docker.network=proxy_channel
        - traefik.http.routers.monitoring-prometheus.entrypoints=web,websecure
        - traefik.http.routers.monitoring-prometheus.middlewares=google-oidc-auth@file,redirectToHttps@file,addTrailingSlash@file
        - traefik.http.routers.monitoring-prometheus.rule=Host(`prometheus.${root_domain}`)
        - traefik.http.services.monitoring-prometheus.loadbalancer.server.port=9090

  node-exporter:
    image: mithucste30/node-exporter:v1.8.2
    networks:
      - host
    command:
      - "--path.rootfs=/rootfs"
    environment:
      - NODE_ID={{.Node.ID}}
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro,rslave
      - /etc/hostname:/etc/nodename

  loki:
    image: grafana/loki:3.1.1
    volumes:
      - ${LOKI_DISK_MOUNT_POINT}:/loki
    ports:
      - "3100:3100"
    deploy:
      placement:
          constraints:
            - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
    configs:
      - source: loki
        target: /config/config.yaml

  promtail:
    image: grafana/promtail:3.3.2
    volumes:
      - /var/log:/var/log  # Modify this to your logs directory
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Access to Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    deploy:
      mode: global
    configs:
      - source: promtail
        target: /etc/promtail/config.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: -logtostderr -docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - prometheus-job=cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:true
      - /sys:/sys:true
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  docker-api-socat:
    image: tecnativa/docker-socket-proxy:0.1
    networks:
      - socat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODES: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    logging:
      driver: none
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

%{ for name, conn in databases ~}
  pg_bouncer_exporter_${name}:
    image: prometheuscommunity/pgbouncer-exporter
    command:
      - "--pgBouncer.connectionString=${conn}/pgbouncer?sslmode=disable&application_name=pgbouncer_exporter"
    restart: unless-stopped
%{ endfor ~}


volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=${NFS_ENDPOINT},nolock,soft,rw"
      device: ":/${NFS_DEVICE}"
  prometheus-data:

networks:
  default:
    name: monitoring_default
    driver: overlay
    attachable: true
  socat:
    name: socat
    driver: overlay
    attachable: true
  host:
    name: host
    driver: host
    external: true
  proxy_channel:
    name: proxy_channel
    external: true
  monitoring_channel:
    name: monitoring_channel
    external: true

configs:
  prometheus:
    name: ${PROMETHEUS_CONFIG_NAME}
    external: true
  loki:
    name: ${LOKI_CONFIG_NAME}
    external: true
  promtail:
    external: true
    name: ${PROMTAIL_CONFIG_NAME}