kubeControllerManager:
  endpoints:
    %{ for endpoint in manager_endpoints ~}
    - ${endpoint}
    %{ endfor ~}

kubeScheduler:
  endpoints:
    %{ for endpoint in scheduler_endpoints ~}
    - ${endpoint}
    %{ endfor ~}


grafana:
  additionalDataSources:
    - name: loki
      type: loki
      url: ${loki_endpoint}
    - name: tempo
      type: tempo
      url: ${tempo_endpoint}