global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'traefik'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'tasks.proxy_proxy'  # Docker Swarm tasks DNS name
        type: 'A'
        port: 8899
