loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h # Must be 24h for TSDB

  storage_config:
    tsdb_shipper:
      active_index_directory: /var/loki/indexes/active
      cache_location: /var/loki/indexes/cache
    filesystem:
      directory: /var/loki/chunks

  commonConfig:
    replication_factor: 1

  storage:
    bucketNames: # Provide dummy values to satisfy the chart
      chunks: "dummy-chunks"
      ruler: "dummy-ruler"
      index: "dummy-index"

  compactor:
    retention_enabled: true
    retention_delete_delay: 2h # Optional: Delay before logs are deleted
    delete_request_store: filesystem

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 6h # Retain logs for 6 hours

  ingester:
    chunk_encoding: snappy

  querier:
    max_concurrent: 4

  pattern_ingester:
    enabled: true

  deploymentMode: SimpleScalable

  memberlist:
    maxJoinBackoff: 5s
    maxJoinAttempts: 15

backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1

gateway:
  service:
    type: ClusterIP

minio:
  enabled: true

lokiCanary:
  extraArgs:
    - -labelname=service
    - -labelvalue=loki-canary
